version: '3'

networks:
  backend:
    external: true

services:
  redirect:
    container_name: redirect
    hostname: redirect
    image: krlsedu/csctracker-redirect
    restart: always
    networks:
      - backend
